name: .NET CI

on:
  push:
    branches: [ main, Platformer-Scene-Engine ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Platformer/Platformer.sln

    - name: Build solution
      run: dotnet build Platformer/Platformer.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test Platformer/Platformer.sln --no-build --configuration Release --logger "trx"